export type ImpactItem = {
  slug: string;
  name: string;
  description: string;
  unitPrice: number;
  icon: string;
  sortOrder: number;
  category: string;
  unitLabel?: string | null;
  imageUrl?: string | null;
  featured?: boolean;
  todayNeed?: boolean;
  futureFlag?: boolean;
  accountingMeaning?: string | null;
  operationalMeaning?: string | null;
  financeApproval?: string;
  gallery?: string | null;
  schemes?: string | null;
};

// Starter amounts. Admin must confirm these against the organisation's accounting/operations.
export const DEFAULT_ITEMS: ImpactItem[] = [
  {
    slug: "meal",
    name: "Sponsor a Warm Meal (Annadana)",
    description: "Wholesome hot lunch or dinner - fragrant rice, nutritious lentils (dal), fresh seasonal vegetables, and warm love for 1 child.",
    unitPrice: 100,
    icon: "meal",
    sortOrder: 1,
    category: "Annadana",
    todayNeed: true,
    featured: true,
    unitLabel: "meal",
    imageUrl: "/media/food.jpg",
    accountingMeaning: "Covers wholesome groceries, grains, lentils, fresh vegetables, cooking fuel, and dairy procured from verified local vendors.",
    operationalMeaning: "Cooked fresh daily in the Ashrama kitchen with pure ingredients, ensuring every child eats three balanced, hot meals with dignity.",
    financeApproval: "approved",
  },
  {
    slug: "fruits",
    name: "Fresh Fruit & Milk Basket",
    description: "Fresh seasonal orchard fruits (apples, bananas, oranges) and pure dairy providing vital daily calcium, vitamins, and morning smiles.",
    unitPrice: 150,
    icon: "fruits",
    sortOrder: 2,
    category: "Annadana",
    todayNeed: true,
    featured: true,
    unitLabel: "basket",
    imageUrl: "/media/fruits.jpg",
    accountingMeaning: "Direct procurement of fresh local orchard fruits and pasteurized milk from Karnataka milk federation.",
    operationalMeaning: "Supplements breakfast and evening snack with vital micronutrients, vitamins, and protein for immunity and active play.",
    financeApproval: "approved",
  },
  {
    slug: "school-kit",
    name: "Complete School Kit & Bag (Vidya)",
    description: "Sturdy school backpack, complete set of notebooks, pencil box, geometry tools, and stationery with a child's name on it.",
    unitPrice: 250,
    icon: "school-kit",
    sortOrder: 3,
    category: "Vidya",
    todayNeed: true,
    featured: true,
    unitLabel: "kit",
    imageUrl: "/media/school-kit.jpg",
    accountingMeaning: "Direct purchase of educational stationery, school course materials, exam fees, and tutoring resources with GST receipts.",
    operationalMeaning: "Gives a child pride and equality in the classroom, knowing they have every tool required to learn, dream, and excel.",
    financeApproval: "approved",
  },
  {
    slug: "education",
    name: "Evening Tutoring & Learning Support",
    description: "Coursebooks, syllabus reference guides, and dedicated small-group evening tutoring in English, Mathematics, and Science.",
    unitPrice: 250,
    icon: "education",
    sortOrder: 4,
    category: "Vidya",
    todayNeed: false,
    featured: false,
    unitLabel: "learner unit",
    imageUrl: "/media/education.jpg",
    accountingMeaning: "Coursebooks, syllabus reference books, and dedicated visiting tutor compensation vouchers.",
    operationalMeaning: "Provides patient, individual academic mentoring so vulnerable children catch up, build confidence, and thrive in school.",
    financeApproval: "approved",
  },
  {
    slug: "uniform",
    name: "School Uniform & Sturdy Footwear",
    description: "Tailored pair of school uniforms, durable black leather shoes, socks, and comfortable everyday clothes.",
    unitPrice: 400,
    icon: "uniform",
    sortOrder: 5,
    category: "Vidya",
    todayNeed: true,
    featured: true,
    unitLabel: "uniform set",
    imageUrl: "/media/learning.jpg",
    accountingMeaning: "Cloth fabric, local tailor stitching charges, and school-specification shoes with audited invoices.",
    operationalMeaning: "Instills peer equality and confidence, ensuring every child walks into the classroom dressed with dignity and pride.",
    financeApproval: "approved",
  },
  {
    slug: "health",
    name: "Pediatric Health & Doctor Care (Arogya)",
    description: "Preventative pediatric health check-ups, doctor consultations, routine prescription medicines, and first-aid replenishments.",
    unitPrice: 500,
    icon: "health",
    sortOrder: 6,
    category: "Arogya",
    todayNeed: true,
    featured: true,
    unitLabel: "health checkup",
    imageUrl: "/media/health.jpg",
    accountingMeaning: "Doctor consultation fees, prescribed medicines, first-aid replenishments, and dental/vision screening clinic invoices.",
    operationalMeaning: "Provides routine pediatric health monitoring, emergency care readiness, and loving attention whenever a child falls unwell.",
    financeApproval: "approved",
  },
  {
    slug: "essentials",
    name: "Personal Hygiene & Care Sanctuary",
    description: "Gentle bath soaps, toothpaste, toothbrush, coconut hair oil, shampoo, clean cotton towel, and grooming toiletries.",
    unitPrice: 300,
    icon: "essentials",
    sortOrder: 7,
    category: "Ashraya",
    todayNeed: false,
    featured: false,
    unitLabel: "care kit",
    imageUrl: "/media/essentials.jpg",
    accountingMeaning: "Bulk procurement of hygiene soaps, toothpaste, oral hygiene kits, and sanitizers audited quarterly.",
    operationalMeaning: "Upholds dignity, health, and cleanliness in daily residential life so every child feels protected and valued.",
    financeApproval: "approved",
  },
  {
    slug: "bedding",
    name: "Cozy Bedding & Warm Blanket Set",
    description: "Clean cotton mattress bedsheet, soft pillow with cover, and a warm winter fleece blanket for peaceful, restorative sleep.",
    unitPrice: 600,
    icon: "bedding",
    sortOrder: 8,
    category: "Ashraya",
    todayNeed: false,
    featured: false,
    unitLabel: "bedding set",
    imageUrl: "/media/garden.jpg",
    accountingMeaning: "Wholesale bedding procurement, heavy-duty blankets, and laundry sanitization supplies.",
    operationalMeaning: "Guarantees a cozy, warm, and secure night's sleep in our clean, well-ventilated dormitories.",
    financeApproval: "approved",
  },
  {
    slug: "activities",
    name: "Sports, Arts & Childhood Play Kit",
    description: "Cricket bats, footballs, carrom boards, drawing sketchbooks, watercolours, and craft supplies for joyful weekends.",
    unitPrice: 350,
    icon: "activities",
    sortOrder: 9,
    category: "Ashraya",
    todayNeed: false,
    featured: false,
    unitLabel: "activity kit",
    imageUrl: "/media/play.jpg",
    accountingMeaning: "Sports equipment, art supplies, musical instruments, and visiting instructor honorariums supported by purchase vouchers.",
    operationalMeaning: "Nurtures creativity, physical fitness, teamwork, and laughter after a long day of studies.",
    financeApproval: "approved",
  },
  {
    slug: "digital-lab",
    name: "Digital Literacy & Computer Skills",
    description: "One month of computer lab access, educational typing software, coding fundamentals, and safe internet research mentoring.",
    unitPrice: 750,
    icon: "digital-lab",
    sortOrder: 10,
    category: "Vidya",
    todayNeed: false,
    featured: false,
    unitLabel: "student month",
    imageUrl: "/media/poster.jpg",
    accountingMeaning: "Broadband connection costs, computer peripheral maintenance, and computer instructor stipends.",
    operationalMeaning: "Bridges the digital divide, preparing young minds for 21st-century careers and modern education.",
    financeApproval: "approved",
  },
  {
    slug: "memorial-meal",
    name: "Sacred Remembrance Meal (Smrithi Seva)",
    description: "Honour the sacred memory of beloved parents or elders by feeding 10 children a wholesome commemorative hot meal.",
    unitPrice: 1000,
    icon: "meal",
    sortOrder: 11,
    category: "Celebrations",
    todayNeed: false,
    featured: true,
    unitLabel: "10 children feast",
    imageUrl: "/media/food.jpg",
    accountingMeaning: "Procurement of wholesome fresh vegetables, pulses, and special grains cooked in memory of donors' elders.",
    operationalMeaning: "Children share silent prayers of gratitude and remembrance, dedicating the nourishment to your departed loved ones.",
    financeApproval: "approved",
  },
  {
    slug: "birthday-feast",
    name: "Grand Birthday Celebration Feast (Utsav)",
    description: "Sponsor a joyous festive lunch with special sweets (Payasam / Laddoo) for all 48 Ashrama children on your birthday or anniversary.",
    unitPrice: 1500,
    icon: "birthday-feast",
    sortOrder: 12,
    category: "Celebrations",
    todayNeed: true,
    featured: true,
    unitLabel: "ashrama feast",
    imageUrl: "/media/food.jpg",
    accountingMeaning: "Special feast grocery list (pure ghee, dry fruits, sweets, special curries, paneer) audited for Ashrama celebrations.",
    operationalMeaning: "Transforms an ordinary day into a festive celebration where the children sing, celebrate, and pray together in your family's honour.",
    financeApproval: "approved",
  },
  {
    slug: "pantry",
    name: "Monthly Kitchen Pantry Staples (50kg Rice & Dal)",
    description: "Wholesale sacks of premium Sona Masoori rice, Toor dal, pure cooking oil, and lentils for the main Ashrama kitchen.",
    unitPrice: 2500,
    icon: "pantry",
    sortOrder: 13,
    category: "Annadana",
    todayNeed: true,
    featured: true,
    unitLabel: "50kg staples",
    imageUrl: "/media/pantry.jpg",
    accountingMeaning: "Wholesale agricultural market committee (APMC) invoices for bulk grain bags and edible oils.",
    operationalMeaning: "Provides the backbone of food security, ensuring the Ashrama kitchen never faces staple ingredient shortages.",
    financeApproval: "approved",
  },
];

export const TODAY_SEED = [
  { title: "Evening study hour", body: "Homework, reading and a quiet corner for every learner. Real daily updates from the Ashrama team will appear here.", category: "Education", imageUrl: "/media/education.jpg" },
  { title: "From the kitchen", body: "What is cooking today, who is helping, and what the kitchen needs this week.", category: "Food", imageUrl: "/media/food.jpg" },
  { title: "Outdoor play", body: "Games, sports and time outside - childhood is part of care.", category: "Activities", imageUrl: "/media/play.jpg" },
  { title: "Health check day", body: "Routine check-ups and wellbeing care, shared when consent and approvals allow.", category: "Healthcare", imageUrl: "/media/health.jpg" },
  { title: "Volunteers at work", body: "Neighbours and volunteers sorting, teaching and lending a hand.", category: "Volunteers", imageUrl: "/media/volunteers.jpg" },
  { title: "A small celebration", body: "Birthdays, festivals and milestones that make a house feel like home.", category: "Celebrations", imageUrl: "/media/community.jpg" },
];

export const CAMPAIGN_SEED = {
  slug: "example-birthday-100-meal-challenge",
  title: "My Birthday - 100 Meal Challenge",
  occasion: "Birthday",
  campaignType: "Individual",
  story:
    "This is an example campaign page showing how Create an Impact will look. Instead of gifts, a supporter asks friends to chip in toward 100 meals at Janaseva Ashrama. Create your own to get a shareable link and QR code.",
  coverImage: "/media/garden.jpg",
  organizerName: "Example supporter",
  goalAmount: 10000,
};

export const DOCS_SEED = [
  { title: "Form 10AC - Provisional 80G Approval (URN: AABTJ7431MF20231, AY 2024-25 to 2026-27)", category: "Tax documents", version: "04-09-2023", publishedOn: "2023-09-04", note: "Order for provisional approval granted to JANA SEVA SAMRUDDI EDUCATION & RURAL DEVELOPMENT SOCIETY R (PAN: AABTJ7431M, DIN: AABTJ7431MF2023101) by Principal Commissioner of Income Tax.", status: "published", sortOrder: 1 },
  { title: "80G certificate", category: "Tax documents", version: null, publishedOn: null, note: "To be published after admin review.", status: "pending", sortOrder: 2 },
  { title: "Registration certificate", category: "Registration", version: null, publishedOn: null, note: "To be published.", status: "pending", sortOrder: 3 },
  { title: "Governance - trustees / committee", category: "Governance", version: null, publishedOn: null, note: "To be published.", status: "pending", sortOrder: 4 },
  { title: "Annual financial report", category: "Financial reports", version: null, publishedOn: null, note: "To be published.", status: "pending", sortOrder: 5 },
  { title: "Child safeguarding policy", category: "Policies", version: null, publishedOn: null, note: "To be published.", status: "pending", sortOrder: 6 },
  { title: "Donation, refund & privacy policy", category: "Policies", version: null, publishedOn: null, note: "To be published.", status: "pending", sortOrder: 7 },
  { title: "Project report - proposed future campus", category: "Project reports", version: null, publishedOn: null, note: "To be published.", status: "pending", sortOrder: 8 },
];

export const METRIC_SEED = [
  { key: "meals", label: "Meals supported", unit: "meals", sortOrder: 1 },
  { key: "education", label: "Education support", unit: "learners supported", sortOrder: 2 },
  { key: "health", label: "Healthcare support", unit: "check-ups / care visits", sortOrder: 3 },
  { key: "activities", label: "Learning activities", unit: "sessions", sortOrder: 4 },
  { key: "community", label: "Community participation", unit: "volunteers & supporters", sortOrder: 5 },
];
