export type ImpactItem = {
  slug: string;
  name: string;
  description: string;
  unitPrice: number;
  icon: string;
  sortOrder: number;
  category: string;
  unitLabel?: string | null;
  imageUrl?: string | null;
  featured?: boolean;
  todayNeed?: boolean;
  futureFlag?: boolean;
  accountingMeaning?: string | null;
  operationalMeaning?: string | null;
  financeApproval?: string;
  gallery?: string | null;
  schemes?: string | null;
};

// Starter amounts. Admin must confirm these against the organisation's accounting/operations.
export const DEFAULT_ITEMS: ImpactItem[] = [
  {
    slug: "bal-seva-milk",
    name: "Bal Seva: 1 Glass Pure Morning Cow Milk (ಶುಭ ಹಾಲು)",
    description: "A warm glass of fresh Nandini cow milk served before dawn with sacred shlokas to 1 growing boy.",
    unitPrice: 11,
    icon: "fruits",
    sortOrder: 0,
    category: "Annadana",
    todayNeed: true,
    featured: true,
    unitLabel: "cup of milk",
    imageUrl: "/media/food.jpg",
    accountingMeaning: "Direct procurement of pasteurized Nandini cow milk from Karnataka Milk Federation for morning nutrition.",
    operationalMeaning: "Nourishes young boys before school with vital calcium and energy to study and grow strong.",
    financeApproval: "approved",
  },
  {
    slug: "dharma-fruit",
    name: "Dharma Jyothi: Fresh Morning Fruit (ಹಣ್ಣು ಸೇವೆ)",
    description: "Fresh banana and seasonal orchard fruit served with evening study snacks to boost immunity.",
    unitPrice: 21,
    icon: "fruits",
    sortOrder: 1,
    category: "Annadana",
    todayNeed: true,
    featured: true,
    unitLabel: "fruit",
    imageUrl: "/media/fruits.jpg",
    accountingMeaning: "Direct purchase of local fresh market bananas and seasonal orchard fruits with local receipt vouchers.",
    operationalMeaning: "Provides essential dietary vitamins and natural sweetness for boys after afternoon classes.",
    financeApproval: "approved",
  },
  {
    slug: "breakfast-shagun",
    name: "Pancha Bhoota: Steaming Hot Breakfast (ತಿಂಡಿ)",
    description: "Steaming hot idlis, sambar, coconut chutney, and warm milk prepared fresh before dawn in the ashrama kitchen.",
    unitPrice: 51,
    icon: "meal",
    sortOrder: 2,
    category: "Annadana",
    todayNeed: true,
    featured: true,
    unitLabel: "breakfast",
    imageUrl: "/media/food.jpg",
    accountingMeaning: "Covers rice rava, urad dal, coconut, sambar spices, and morning cooking gas fuel.",
    operationalMeaning: "Ensures no boy leaves for government school on an empty stomach.",
    financeApproval: "approved",
  },
  {
    slug: "meal",
    name: "Punya Annadana: Full Hot Lunch or Dinner (ಊಟ)",
    description: "Wholesome hot lunch or dinner - fragrant rice, nutritious lentils (dal), fresh seasonal vegetables, and warm love for 1 child.",
    unitPrice: 101,
    icon: "meal",
    sortOrder: 3,
    category: "Annadana",
    todayNeed: true,
    featured: true,
    unitLabel: "meal",
    imageUrl: "/media/annadana-hall-hd.jpg",
    accountingMeaning: "Covers wholesome groceries, grains, lentils, fresh vegetables, cooking fuel, and dairy procured from verified local vendors.",
    operationalMeaning: "Cooked fresh daily in the Ashrama kitchen with pure ingredients, ensuring every child eats three balanced, hot meals with dignity.",
    financeApproval: "approved",
  },
  {
    slug: "fruits",
    name: "Fresh Fruit & Milk Basket",
    description: "Fresh seasonal orchard fruits (apples, bananas, oranges) and pure dairy providing vital daily calcium, vitamins, and morning smiles.",
    unitPrice: 151,
    icon: "fruits",
    sortOrder: 2,
    category: "Annadana",
    todayNeed: true,
    featured: true,
    unitLabel: "basket",
    imageUrl: "/media/banana-leaf-feast.jpg",
    accountingMeaning: "Direct procurement of fresh local orchard fruits and pasteurized milk from Karnataka milk federation.",
    operationalMeaning: "Supplements breakfast and evening snack with vital micronutrients, vitamins, and protein for immunity and active play.",
    financeApproval: "approved",
  },
  {
    slug: "school-kit",
    name: "Complete School Kit & Bag (Vidya)",
    description: "Sturdy school backpack, complete set of notebooks, pencil box, geometry tools, and stationery with a child's name on it.",
    unitPrice: 251,
    icon: "school-kit",
    sortOrder: 3,
    category: "Vidya",
    todayNeed: true,
    featured: true,
    unitLabel: "kit",
    imageUrl: "/media/art-drawings.jpg",
    accountingMeaning: "Direct purchase of educational stationery, school course materials, exam fees, and tutoring resources with GST receipts.",
    operationalMeaning: "Gives a child pride and equality in the classroom, knowing they have every tool required to learn, dream, and excel.",
    financeApproval: "approved",
  },
  {
    slug: "education",
    name: "Evening Tutoring & Learning Support",
    description: "Coursebooks, syllabus reference guides, and dedicated small-group evening tutoring in English, Mathematics, and Science.",
    unitPrice: 251,
    icon: "education",
    sortOrder: 4,
    category: "Vidya",
    todayNeed: false,
    featured: false,
    unitLabel: "learner unit",
    imageUrl: "/media/abacus-math-class.jpg",
    accountingMeaning: "Coursebooks, syllabus reference books, and dedicated visiting tutor compensation vouchers.",
    operationalMeaning: "Provides patient, individual academic mentoring so vulnerable children catch up, build confidence, and thrive in school.",
    financeApproval: "approved",
  },
  {
    slug: "uniform",
    name: "School Uniform & Sturdy Footwear",
    description: "Tailored pair of school uniforms, durable black leather shoes, socks, and comfortable everyday clothes.",
    unitPrice: 501,
    icon: "uniform",
    sortOrder: 5,
    category: "Vidya",
    todayNeed: true,
    featured: true,
    unitLabel: "uniform set",
    imageUrl: "/media/boys-group-red-assembly.jpg",
    accountingMeaning: "Cloth fabric, local tailor stitching charges, and school-specification shoes with audited invoices.",
    operationalMeaning: "Instills peer equality and confidence, ensuring every child walks into the classroom dressed with dignity and pride.",
    financeApproval: "approved",
  },
  {
    slug: "health",
    name: "Pediatric Health & Doctor Care (Arogya)",
    description: "Preventative pediatric health check-ups, doctor consultations, routine prescription medicines, and first-aid replenishments.",
    unitPrice: 501,
    icon: "health",
    sortOrder: 6,
    category: "Arogya",
    todayNeed: true,
    featured: true,
    unitLabel: "health checkup",
    imageUrl: "/media/yoga-day.jpg",
    accountingMeaning: "Doctor consultation fees, prescribed medicines, first-aid replenishments, and dental/vision screening clinic invoices.",
    operationalMeaning: "Provides routine pediatric health monitoring, emergency care readiness, and loving attention whenever a child falls unwell.",
    financeApproval: "approved",
  },
  {
    slug: "health-camp",
    name: "Rural Health & Eye Screening Camp Kit",
    description: "Portable diagnostics, blood pressure vitals, eye refraction testing kits, and essential emergency medicines for community outreach.",
    unitPrice: 1201,
    icon: "health",
    sortOrder: 61,
    category: "Arogya",
    todayNeed: false,
    featured: true,
    unitLabel: "camp kit",
    imageUrl: "/media/yoga-tadasana.jpg",
    accountingMeaning: "Medical diagnostics consumables, sterile examination kits, and volunteer doctor transit stipends with GST bills.",
    operationalMeaning: "Empowers monthly free health camps in remote villages and peri-urban slums where families cannot afford clinic visits.",
    financeApproval: "approved",
  },
  {
    slug: "clean-water",
    name: "Safe Drinking Water & Sanitation Unit",
    description: "Heavy-duty water purification filter replacements, safe drinking dispensers, and child hygiene sanitization units for disease prevention.",
    unitPrice: 351,
    icon: "essentials",
    sortOrder: 62,
    category: "Arogya",
    todayNeed: true,
    featured: false,
    unitLabel: "filter unit",
    imageUrl: "/media/lawn-cheer-circle.jpg",
    accountingMeaning: "RO filter cartridge replacements, water quality testing lab kits, and hygiene sanitizers with audited GST invoices.",
    operationalMeaning: "Prevents waterborne illnesses, ensuring 25 children drink 100% safe, clean water every single day.",
    financeApproval: "approved",
  },
  {
    slug: "essentials",
    name: "Personal Hygiene & Care Sanctuary",
    description: "Gentle bath soaps, toothpaste, toothbrush, coconut hair oil, shampoo, clean cotton towel, and grooming toiletries.",
    unitPrice: 251,
    icon: "essentials",
    sortOrder: 7,
    category: "Ashraya",
    todayNeed: false,
    featured: false,
    unitLabel: "care kit",
    imageUrl: "/media/evening-snacks-gathering.jpg",
    accountingMeaning: "Bulk procurement of hygiene soaps, toothpaste, oral hygiene kits, and sanitizers audited quarterly.",
    operationalMeaning: "Upholds dignity, health, and cleanliness in daily residential life so every child feels protected and valued.",
    financeApproval: "approved",
  },
  {
    slug: "bedding",
    name: "Cozy Bedding & Warm Blanket Set",
    description: "Clean cotton mattress bedsheet, soft pillow with cover, and a warm winter fleece blanket for peaceful, restorative sleep.",
    unitPrice: 501,
    icon: "bedding",
    sortOrder: 8,
    category: "Ashraya",
    todayNeed: false,
    featured: false,
    unitLabel: "bedding set",
    imageUrl: "/media/evening-satsang.jpg",
    accountingMeaning: "Wholesale bedding procurement, heavy-duty blankets, and laundry sanitization supplies.",
    operationalMeaning: "Guarantees a cozy, warm, and secure night's sleep in our clean, well-ventilated dormitories.",
    financeApproval: "approved",
  },
  {
    slug: "activities",
    name: "Sports, Arts & Childhood Play Kit",
    description: "Cricket bats, footballs, carrom boards, drawing sketchbooks, watercolours, and craft supplies for joyful weekends.",
    unitPrice: 251,
    icon: "activities",
    sortOrder: 9,
    category: "Ashraya",
    todayNeed: false,
    featured: false,
    unitLabel: "activity kit",
    imageUrl: "/media/carrom-play.jpg",
    accountingMeaning: "Sports equipment, art supplies, musical instruments, and visiting instructor honorariums supported by purchase vouchers.",
    operationalMeaning: "Nurtures creativity, physical fitness, teamwork, and laughter after a long day of studies.",
    financeApproval: "approved",
  },
  {
    slug: "digital-lab",
    name: "Digital Literacy & Computer Skills",
    description: "One month of computer lab access, educational typing software, coding fundamentals, and safe internet research mentoring.",
    unitPrice: 751,
    icon: "digital-lab",
    sortOrder: 10,
    category: "Vidya",
    todayNeed: false,
    featured: false,
    unitLabel: "student month",
    imageUrl: "/media/mentorship-story-circle.jpg",
    accountingMeaning: "Broadband connection costs, computer peripheral maintenance, and computer instructor stipends.",
    operationalMeaning: "Bridges the digital divide, preparing young minds for 21st-century careers and modern education.",
    financeApproval: "approved",
  },
  {
    slug: "memorial-meal",
    name: "Sacred Remembrance Meal (Smrithi Seva)",
    description: "Honour the sacred memory of beloved parents or elders by feeding 10 children a wholesome commemorative hot meal.",
    unitPrice: 1001,
    icon: "meal",
    sortOrder: 11,
    category: "Celebrations",
    todayNeed: false,
    featured: true,
    unitLabel: "10 children feast",
    imageUrl: "/media/boys-meal-gratitude.jpg",
    accountingMeaning: "Procurement of wholesome fresh vegetables, pulses, and special grains cooked in memory of donors' elders.",
    operationalMeaning: "Children share silent prayers of gratitude and remembrance, dedicating the nourishment to your departed loved ones.",
    financeApproval: "approved",
  },
  {
    slug: "birthday-feast",
    name: "Grand Birthday Celebration Feast (Utsav)",
    description: "Sponsor a joyous festive lunch with special sweets (Payasam / Laddoo) for all 25 Ashrama children on your birthday or anniversary.",
    unitPrice: 1501,
    icon: "birthday-feast",
    sortOrder: 12,
    category: "Celebrations",
    todayNeed: true,
    featured: true,
    unitLabel: "ashrama feast",
    imageUrl: "/media/birthday-cake-celebration.jpg",
    accountingMeaning: "Special feast grocery list (pure ghee, dry fruits, sweets, special curries, paneer) audited for Ashrama celebrations.",
    operationalMeaning: "Transforms an ordinary day into a festive celebration where the children sing, celebrate, and pray together in your family's honour.",
    financeApproval: "approved",
  },
  {
    slug: "pantry",
    name: "Monthly Kitchen Pantry Staples (50kg Rice & Dal)",
    description: "Wholesale sacks of premium Sona Masoori rice, Toor dal, pure cooking oil, and lentils for the main Ashrama kitchen.",
    unitPrice: 2501,
    icon: "pantry",
    sortOrder: 13,
    category: "Annadana",
    todayNeed: true,
    featured: true,
    unitLabel: "50kg staples",
    imageUrl: "/media/banana-leaf-feast.jpg",
    accountingMeaning: "Wholesale agricultural market committee (APMC) invoices for bulk grain bags and edible oils.",
    operationalMeaning: "Provides the backbone of food security, ensuring the Ashrama kitchen never faces staple ingredient shortages.",
    financeApproval: "approved",
  },
  // ── EXACT 5 OFFICIAL SUPPORT TIERS & PRICING (Supporters Form) ──
  {
    slug: "tier-1-full-day",
    name: "Full Day Food for All 25 Boys (Tier 1)",
    description: "Complete daily Annadana: hot breakfast, nutritious lunch, evening snacks & dinner cooked fresh for all 25 resident boys.",
    unitPrice: 4500,
    icon: "meal",
    sortOrder: 10,
    category: "Official Tiers",
    todayNeed: true,
    featured: true,
    unitLabel: "day (all 25 boys)",
    imageUrl: "/media/annadana-hall-hd.jpg",
    accountingMeaning: "Covers 3 wholesome meals (breakfast, lunch, dinner) and snacks for 25 boys with local grain/vegetable invoices.",
    operationalMeaning: "Ensures all 25 resident boys receive full daily nutrition and dignity under Caregiver supervision.",
    financeApproval: "approved",
  },
  {
    slug: "tier-1-two-times",
    name: "Two Times Food for All 25 Boys (Tier 1)",
    description: "Wholesome lunch and dinner (rice, sambar, dal, fresh vegetables) prepared with love for all 25 boys.",
    unitPrice: 3000,
    icon: "meal",
    sortOrder: 11,
    category: "Official Tiers",
    todayNeed: true,
    featured: false,
    unitLabel: "lunch & dinner",
    imageUrl: "/media/annadana-hall-hd.jpg",
    accountingMeaning: "Covers lunch and dinner for all 25 boys with audited vegetable and grocery vouchers.",
    operationalMeaning: "Sustains the main noon and evening dining sessions for all resident boys.",
    financeApproval: "approved",
  },
  {
    slug: "tier-1-one-time",
    name: "One Time Meal for All 25 Boys (Tier 1)",
    description: "Single nutritious hot meal (Annadana lunch or dinner) for all 25 resident children in the dining hall.",
    unitPrice: 2500,
    icon: "meal",
    sortOrder: 12,
    category: "Official Tiers",
    todayNeed: true,
    featured: false,
    unitLabel: "single meal",
    imageUrl: "/media/banana-leaf-feast.jpg",
    accountingMeaning: "Covers a single full-hall meal sitting for 25 boys with fresh cooking ingredients.",
    operationalMeaning: "Fulfills one major daily meal with dignity and warmth.",
    financeApproval: "approved",
  },
  {
    slug: "tier-2-month-4",
    name: "1 Month Food for 4 Boys (Tier 2)",
    description: "Comprehensive 30-day grocery rations (rice, lentils, dairy, vegetables) sustaining 4 resident boys for a full month.",
    unitPrice: 6000,
    icon: "pantry",
    sortOrder: 20,
    category: "Official Tiers",
    todayNeed: true,
    featured: true,
    unitLabel: "4 boys / month",
    imageUrl: "/media/banana-leaf-feast.jpg",
    accountingMeaning: "Wholesale grain market procurement of monthly staples dedicated to 4 children.",
    operationalMeaning: "Guarantees a full month of food security and uninterrupted nutrition for 4 boys.",
    financeApproval: "approved",
  },
  {
    slug: "tier-2-month-2",
    name: "1 Month Food for 2 Boys (Tier 2)",
    description: "Essential 30-day monthly nourishment kit ensuring two boys eat balanced nutritious meals daily.",
    unitPrice: 4000,
    icon: "pantry",
    sortOrder: 21,
    category: "Official Tiers",
    todayNeed: false,
    featured: false,
    unitLabel: "2 boys / month",
    imageUrl: "/media/prayer-meals.jpg",
    accountingMeaning: "Monthly grocery staples and vegetable allocation for 2 boys.",
    operationalMeaning: "Sponsors two children's entire nutrition for 30 consecutive days.",
    financeApproval: "approved",
  },
  {
    slug: "tier-2-month-1",
    name: "1 Month Food for 1 Boy (Tier 2)",
    description: "Complete monthly food sponsorship ensuring 1 child is fully nourished for 30 consecutive days.",
    unitPrice: 2000,
    icon: "pantry",
    sortOrder: 22,
    category: "Official Tiers",
    todayNeed: false,
    featured: false,
    unitLabel: "1 boy / month",
    imageUrl: "/media/boys-meal-gratitude.jpg",
    accountingMeaning: "Monthly food budget for 1 child covering breakfast, lunch, and dinner.",
    operationalMeaning: "Ensures one child has steady daily nourishment and growth.",
    financeApproval: "approved",
  },
  {
    slug: "tier-3-cloth-8",
    name: "1 Set Cloth for 8 Boys (Tier 3)",
    description: "Tailored high-durability cotton outfits, traditional festival kurtas, and daily casual clothing sets for 8 boys.",
    unitPrice: 4800,
    icon: "uniform",
    sortOrder: 30,
    category: "Official Tiers",
    todayNeed: false,
    featured: true,
    unitLabel: "8 boys cloth sets",
    imageUrl: "/media/boys-group-red-assembly.jpg",
    accountingMeaning: "Fabric wholesale purchase and local tailoring charges for 8 sets of clothes.",
    operationalMeaning: "Provides 8 boys with brand-new, clean, dignified clothing for daily wear and celebrations.",
    financeApproval: "approved",
  },
  {
    slug: "tier-3-cloth-6",
    name: "1 Set Cloth for 6 Boys (Tier 3)",
    description: "Durable everyday cotton dress sets and traditional attire stitched for 6 resident children.",
    unitPrice: 3600,
    icon: "uniform",
    sortOrder: 31,
    category: "Official Tiers",
    todayNeed: false,
    featured: false,
    unitLabel: "6 boys cloth sets",
    imageUrl: "/media/boys-assembly-maroon.jpg",
    accountingMeaning: "Fabric and tailor stitching invoices for 6 children's clothing sets.",
    operationalMeaning: "Refreshes everyday wardrobes for 6 growing boys.",
    financeApproval: "approved",
  },
  {
    slug: "tier-3-cloth-3",
    name: "1 Set Cloth for 3 Boys (Tier 3)",
    description: "Comfortable everyday cotton clothing sets and festival wear for 3 growing boys.",
    unitPrice: 1800,
    icon: "uniform",
    sortOrder: 32,
    category: "Official Tiers",
    todayNeed: false,
    featured: false,
    unitLabel: "3 boys cloth sets",
    imageUrl: "/media/flag-assembly.jpg",
    accountingMeaning: "Clothing fabric and stitching for 3 boys with verified receipts.",
    operationalMeaning: "Dignifies 3 boys with fresh, well-fitted everyday clothes.",
    financeApproval: "approved",
  },
  {
    slug: "tier-4-edu-12",
    name: "1 Month Education for 12 Boys (Tier 4)",
    description: "Sponsor monthly tuition, school notebooks, exam fees, stationery kits, and evening tutoring for 12 boys.",
    unitPrice: 9600,
    icon: "education",
    sortOrder: 40,
    category: "Official Tiers",
    todayNeed: false,
    featured: true,
    unitLabel: "12 boys / month",
    imageUrl: "/media/art-drawings.jpg",
    accountingMeaning: "School fees, syllabus notebooks, and visiting tutor compensation vouchers for 12 boys.",
    operationalMeaning: "Empowers 12 children with academic mentoring, books, and classroom confidence.",
    financeApproval: "approved",
  },
  {
    slug: "tier-4-edu-8",
    name: "1 Month Education for 8 Boys (Tier 4)",
    description: "Monthly academic mentoring, school supplies, and after-school tuition classes for 8 boys.",
    unitPrice: 6400,
    icon: "education",
    sortOrder: 41,
    category: "Official Tiers",
    todayNeed: false,
    featured: false,
    unitLabel: "8 boys / month",
    imageUrl: "/media/essay-competition.jpg",
    accountingMeaning: "Educational materials and tutor stipends for 8 children.",
    operationalMeaning: "Keeps 8 boys on track in math, science, and languages.",
    financeApproval: "approved",
  },
  {
    slug: "tier-4-edu-4",
    name: "1 Month Education for 4 Boys (Tier 4)",
    description: "One month of personalized academic coaching, textbooks, and stationery materials for 4 children.",
    unitPrice: 3200,
    icon: "education",
    sortOrder: 42,
    category: "Official Tiers",
    todayNeed: false,
    featured: false,
    unitLabel: "4 boys / month",
    imageUrl: "/media/handprint-workshop.jpg",
    accountingMeaning: "Stationery and evening teacher assistance for 4 students.",
    operationalMeaning: "Provides patient learning support for 4 young scholars.",
    financeApproval: "approved",
  },
  {
    slug: "tier-5-edu-year-3",
    name: "1 Year Full Schooling for 3 Boys (Tier 5)",
    description: "Annual comprehensive education covering school admissions, textbook bundles, school bags, shoes, uniforms, and mentorship for 3 boys.",
    unitPrice: 28800,
    icon: "school-kit",
    sortOrder: 50,
    category: "Official Tiers",
    todayNeed: false,
    featured: true,
    unitLabel: "3 boys / full year",
    imageUrl: "/media/excellence-certificates.jpg",
    accountingMeaning: "Full annual school fees, board textbook sets, uniforms, and school bags with school receipts.",
    operationalMeaning: "Completely funds an entire academic year of schooling and transformation for 3 boys.",
    financeApproval: "approved",
  },
  {
    slug: "tier-5-edu-year-2",
    name: "1 Year Full Schooling for 2 Boys (Tier 5)",
    description: "Complete 12-month educational sponsorship and academic materials for 2 children.",
    unitPrice: 19200,
    icon: "school-kit",
    sortOrder: 51,
    category: "Official Tiers",
    todayNeed: false,
    featured: false,
    unitLabel: "2 boys / full year",
    imageUrl: "/media/excellence-certificates.jpg",
    accountingMeaning: "Comprehensive 12-month school expenses and materials for 2 boys.",
    operationalMeaning: "Secures a whole year of uninterrupted education for two children.",
    financeApproval: "approved",
  },
  {
    slug: "tier-5-edu-year-1",
    name: "1 Year Full Schooling for 1 Boy (Tier 5)",
    description: "Sponsor a child's complete academic year with school tuition, textbooks, uniforms, and shoes.",
    unitPrice: 9600,
    icon: "school-kit",
    sortOrder: 52,
    category: "Official Tiers",
    todayNeed: false,
    featured: false,
    unitLabel: "1 boy / full year",
    imageUrl: "/media/excellence-certificates.jpg",
    accountingMeaning: "Annual schooling fee, textbooks, exam fees, and uniform for 1 child.",
    operationalMeaning: "Transforms one boy's future by sponsoring his entire school year.",
    financeApproval: "approved",
  },
];

export const TODAY_SEED = [
  { title: "Morning Annadana Prayer", body: "All 25 resident boys folding hands before steel meal plates, chanting universal shlokas of gratitude before breakfast in our main hall.", category: "Annadana", imageUrl: "/media/annadana-hall-hd.jpg" },
  { title: "Bale Ele Oota (Banana Leaf Feast)", body: "Traditional South Indian festival meal served hot on fresh green plantain leaves, celebrated with joy and dignity.", category: "Annadana", imageUrl: "/media/banana-leaf-feast.jpg" },
  { title: "Classroom Art & Creative Drawings", body: "Boys proudly displaying handmade sketches, creative posters, and drawings under the Janaseva banner.", category: "Education", imageUrl: "/media/art-drawings.jpg" },
  { title: "International Yoga Day & Meditation", body: "Practicing Padmasana and Sukhasana breathing techniques on striped mats for mental clarity and physical strength.", category: "Health", imageUrl: "/media/yoga-day.jpg" },
  { title: "Patriotic Flag Hoisting & Rangoli", body: "Independence Day celebrations with tricolour Bharat map rangoli, patriotic anthems, and disciplined flag salutes.", category: "Celebrations", imageUrl: "/media/flag-hoisting-rangoli.jpg" },
  { title: "Birthday Cake Cutting with Well-Wisher", body: "Special birthday celebration with donor family, fresh red rose petals, cake cutting, and collective singing of blessings.", category: "Celebrations", imageUrl: "/media/birthday-cake-celebration.jpg" },
  { title: "Courtyard Games & Carrom Tournaments", body: "Healthy competitive spirit with carrom matches, chess, and joyous outdoor play fostering deep brotherly bonding.", category: "Activities", imageUrl: "/media/carrom-play.jpg" },
  { title: "Academic & Competition Excellence", body: "Boys proudly holding official certificates of achievement from Bengaluru inter-school cultural and talent competitions.", category: "Education", imageUrl: "/media/excellence-certificates.jpg" },
];

export const CAMPAIGN_SEED = {
  slug: "example-birthday-100-meal-challenge",
  title: "My Birthday - 100 Meal Challenge",
  occasion: "Birthday",
  campaignType: "Individual",
  story:
    "This is an example campaign page showing how Create an Impact will look. Instead of gifts, a supporter asks friends to chip in toward 100 meals at Janaseva Ashrama. Create your own to get a shareable link and QR code.",
  coverImage: "/media/janaseva-ashrama-original.jpg",
  organizerName: "Example supporter",
  goalAmount: 10000,
};

export const DOCS_SEED = [
  {
    title: "Form 10AC - Section 80G Provisional Approval (URN: AABTJ7431MF20231)",
    category: "Tax documents",
    version: "AY 2024-25 to 2026-27",
    publishedOn: "2023-09-04",
    fileUrl: "/documents/form-10ac-80g-approval.pdf",
    note: "Order for provisional approval under Section 80G granted to JANA SEVA SAMRUDDI EDUCATION & RURAL DEVELOPMENT SOCIETY R (PAN: AABTJ7431M, DIN: AABTJ7431MF2023101) by Principal Commissioner of Income Tax.",
    status: "published",
    sortOrder: 1,
  },
  {
    title: "Govt of Karnataka Child Care Institution Registration (Form 28, JJ Act 2015)",
    category: "Registration",
    version: "Reg No: KA18CH0242 (2025-2030)",
    publishedOn: "2025-03-27",
    fileUrl: "/documents/jj-act-child-care-institution-registration-form-28.pdf",
    note: "Official Certificate of Registration from Directorate of Child Protection, Government of Karnataka under Section 41 of JJ Act 2015. Registered Children Home for Boys with approved capacity of 25 children.",
    status: "published",
    sortOrder: 2,
  },
  {
    title: "Ministry of Corporate Affairs CSR Registration Certificate (Form CSR-1)",
    category: "Corporate & CSR",
    version: "CSR00078800 (17-09-2024)",
    publishedOn: "2024-09-17",
    fileUrl: "/documents/mca-csr-1-registration-certificate.pdf",
    note: "Official approval from ROC-Delhi / Ministry of Corporate Affairs (SRN-F98737448) certifying entity for undertaking CSR activities under Section 135 of Companies Act, 2013.",
    status: "published",
    sortOrder: 3,
  },
  {
    title: "Section 12AA Registration Order — 100% Tax-Exempt Charitable Entity",
    category: "Tax documents",
    version: "AY 2018-19 onwards",
    publishedOn: "2018-09-18",
    fileUrl: "/documents/section-12aa-registration-certificate.pdf",
    note: "Official Order from CIT (Exemptions) Bangalore granting Section 12AA registration (Order No: ITBA/EXM/S/12AA/2018-19/1012296034(1), Reg No: CIT(EXEMPTION S) BANGALORE/12AA/2018-19/A/10403).",
    status: "published",
    sortOrder: 4,
  },
  {
    title: "Income Tax Department Permanent Account Number (PAN Card)",
    category: "Registration",
    version: "PAN: AABTJ7431M (Est. 02/04/2013)",
    publishedOn: "2013-04-02",
    fileUrl: "/documents/society-pan-card.pdf",
    note: "Permanent Account Number card of Janaseva Samruddi Education & Rural Development Society R issued by Income Tax Department, Govt of India.",
    status: "published",
    sortOrder: 5,
  },
  {
    title: "Child Safeguarding & Protection Policy",
    category: "Policies",
    version: "v2025.1",
    publishedOn: "2025-01-10",
    fileUrl: null,
    note: "Strict protocols for child privacy, visitor screening, photography consent, and psychological well-being.",
    status: "published",
    sortOrder: 6,
  },
  {
    title: "Donation, 80G Tax Receipt & Refund Policy",
    category: "Policies",
    version: "v2024.3",
    publishedOn: "2024-06-01",
    fileUrl: null,
    note: "Clear operational principles governing donation allocation, 80G certificates, transparency, and refund requests.",
    status: "published",
    sortOrder: 7,
  },
  {
    title: "Proposed Future Permanent Campus Blueprint & Vision Plan",
    category: "Project reports",
    version: "Phase-1",
    publishedOn: "2024-11-15",
    fileUrl: null,
    note: "Architectural blueprint and sustainability roadmap for the upcoming permanent campus in Bangalore.",
    status: "published",
    sortOrder: 8,
  },
];

export const METRIC_SEED = [
  { key: "meals", label: "Meals supported", unit: "meals", sortOrder: 1 },
  { key: "education", label: "Education support", unit: "learners supported", sortOrder: 2 },
  { key: "health", label: "Healthcare support", unit: "check-ups / care visits", sortOrder: 3 },
  { key: "activities", label: "Learning activities", unit: "sessions", sortOrder: 4 },
  { key: "community", label: "Community participation", unit: "volunteers & supporters", sortOrder: 5 },
];
